AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  ETLOrchestratorwithLambda

  Sample SAM Template for ETLOrchestratorwithLambda

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30

Resources:
  MySqsQueue:
    Type: AWS::SQS::Queue
    Properties:
        QueueName: my-queue
        VisibilityTimeout: 60

  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: .
      Handler: src.app.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64

#      Policies:
#        -SQSPollerPolicy:
#            QueueArn: !GetAtt MySqsQueue.Arn
      Policies:
        - SQSSendMessagePolicy:
            QueueName: !GetAtt MySqsQueue.Arn

      Events:
        SqsTrigger:
          Type: SQS
          Properties:
            Queue: !GetAtt MySqsQueue.Arn
            BatchSize: 1
            Enabled: true


Outputs:

  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn

  SqsQueueUrl:
    Description: SQS Queue URL
    Value: !Ref MySqsQueue

  SqsQueueArn:
    Description: SQS Queue ARN
    Value: !GetAtt MySqsQueue.Arn