AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  ETLOrchestratorwithLambda

Globals:
  Function:
    Runtime: python3.12
    Architectures:
      - x86_64
    Timeout: 300

Resources:
  # ------------------ SQS ------------------
  MySqsQueue:
    Type: AWS::SQS::Queue
    Properties:
      VisibilityTimeout: 300
  # ------------------ RDS (Minimal MySQL) ------------------
  OrdersDB:
    Type: AWS::RDS::DBInstance
    Properties:
      Engine: mysql
      DBInstanceClass: db.t3.micro
      AllocatedStorage: "20"
      DBName: batch1
      MasterUsername: admin
      MasterUserPassword: MyStrongPassword123!
      PubliclyAccessible: true
  # ------------------ Producer Lambda (API → SQS) ------------------
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: src.app.lambda_handler
      Environment:
        Variables:
          QUEUE_URL: https://sqs.us-east-1.amazonaws.com/082291634475/ETLOrchestratorwithLambda-MySqsQueue-D6wPfY24fbWI
      Policies:
        - SQSSendMessagePolicy:
            QueueName: !Ref MySqsQueue
      Events:
        OrdersApi:
          Type: Api
          Properties:
            Path: /orders
            Method: post
  # ------------------ Consumer Lambda (SQS → RDS) ------------------
  ConsumersFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: src.consumer.lambda_handler
      Environment:
        Variables:
          DB_HOST: database-1.c6z8q4esgrdk.us-east-1.rds.amazonaws.com
          DB_NAME: batch1
          DB_USER: admin
          DB_PASSWORD: Mohan2026
      Policies:
        - SQSPollerPolicy:
            QueueName: !Ref MySqsQueue
      Events:
        SqsTrigger:
          Type: SQS
          Properties:
            Queue: !GetAtt MySqsQueue.Arn
            BatchSize: 1
            Enabled: true


